functionality to suggest default configs

diff --git a/all b/all
--- a/all
+++ b/all
@@ -1,10 +1,21 @@
 #!/bin/bash
 
 function check() {
+    checkFileExistence phpcs.xml
     phpcs $1
-    phpmd $1 text 'cleancode,codesize,controversial,design,naming,unusedcode' --exclude=vendor
+    checkFileExistence phpmd.xml
+    phpmd $1 text phpmd.xml
+    checkFileExistence phpstan.neon
     phpstan analyze --level=7 $1
+    checkFileExistence phpcpd.xml
     phpcpd --fuzzy --exclude vendor $1
+}
+
+function checkFileExistence() {
+    if [ ! -f $1 ]; then
+        echo "File $1 not found!"
+        exit 1
+    fi
 }
 
 if [ $# -eq 0 ]
